#!/bin/bash

###############################################################################
#                                                                             #
#                                 Print Usage                                 #
#                                                                             #
###############################################################################
function usage {
    echo "'$0' Execute a go cross compilation platform with gox"
    echo "Usage : $0 root project"
    echo "    root    : Go project root directory (ex: /src)"
    echo "    project : Go project directory name (ex: github.com/example/go"
    echo ""
}

# Check if help is requested
if [[ $1 == "--help" ]] ; then
    usage
    exit 0
fi

# Check user input
if [[ $# -lt 2 || $# -ge 3 ]]; then
    usage
    exit 1
fi

# Check user right
if [ `id -u` -ne 0 ]; then
   error "This script must be run as root in the docker container"
   exit 255
fi

set -eo pipefail

GOSOUCE=${1%/}
GOPROJECT=${2}

cp -R $GOSOUCE/$GOPROJECT/* $GOPATH/src
cd $GOPATH/src
cd $GOPROJECT
go get
gox
cp -R $GOPATH/src/$GOPROJECT/* $GOSOUCE/$GOPROJECT